"""Operations, OR-Tools Optimization, and What-If Simulation API endpoints."""

from typing import Any

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.models.optimization import Recommendation
from app.services.optimization.vrp_service import vrp_service
from app.services.simulation.simulation_service import simulation_service

router = APIRouter()


class SimulationRequest(BaseModel):
    scenario_type: str = (
        "SEVERE_WEATHER"  # NORMAL, SEVERE_WEATHER, ROUTE_BLOCKAGE, DEMAND_SURGE, REPLENISHMENT_DISPATCH
    )


@router.post(
    "/optimization/solve-dispatch",
    summary="Solve OR-Tools Multi-Depot CVRPTW Fleet Dispatch",
    description="Optimizes fleet vehicle routes and cargo allocation with time-windows and terrain/weather cost impedance.",
)
async def solve_fleet_dispatch(
    max_solve_time_seconds: int = Query(5, ge=1, le=30),
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Execute OR-Tools CVRPTW solver."""
    return await vrp_service.solve_replenishment_dispatch(
        db=db,
        max_solve_time_seconds=max_solve_time_seconds,
    )


@router.get(
    "/optimization/recommendations",
    summary="List Optimization Recommendations",
    description="Returns proposed dispatch, routing, and rationing recommendations generated by OR-Tools.",
)
async def list_recommendations(
    status: str | None = Query(None, description="Filter by status (PROPOSED, ACCEPTED, EXECUTED)"),
    db: AsyncSession = Depends(get_db),
) -> list[dict[str, Any]]:
    """Retrieve actionable recommendations."""
    query = select(Recommendation).order_by(Recommendation.created_at.desc()).limit(50)
    if status:
        query = query.where(Recommendation.status == status)

    res = await db.execute(query)
    recs = res.scalars().all()

    return [
        {
            "id": str(r.id),
            "optimization_run_id": str(r.optimization_run_id),
            "recommendation_type": r.recommendation_type,
            "details": r.details,
            "status": r.status,
            "created_at": r.created_at.isoformat(),
        }
        for r in recs
    ]


@router.post(
    "/simulation/scenario",
    summary="Execute What-If Stress-Test Scenario",
    description="Simulates network resilience under disruption scenarios (SEVERE_WEATHER, ROUTE_BLOCKAGE, DEMAND_SURGE, REPLENISHMENT_DISPATCH).",
)
async def execute_simulation_scenario(
    request: SimulationRequest,
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Execute What-If simulation."""
    return await simulation_service.run_scenario(
        scenario_type=request.scenario_type,
        db=db,
    )
