"""Alert SQLAlchemy model."""

import uuid
from datetime import UTC, datetime

from sqlalchemy import Boolean, Column, DateTime, Float, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db.base import Base


class Alert(Base):
    """
    Predictive risk alert generated by the Inventory Risk Engine in Phase 5.
    Contains mathematical explanations and exact projected stockout timestamps.
    """

    __tablename__ = "alerts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    location_id = Column(UUID(as_uuid=True), ForeignKey("locations.id", ondelete="CASCADE"), nullable=False, index=True)
    item_id = Column(UUID(as_uuid=True), ForeignKey("supply_items.id", ondelete="CASCADE"), nullable=True, index=True)

    alert_type = Column(
        String(50), nullable=False, index=True
    )  # STOCKOUT_IMMINENT, LOW_STOCK, LEAD_TIME_RISK, ROUTE_BLOCKED, DEMAND_SURGE
    severity = Column(String(20), nullable=False, index=True)  # CRITICAL, WARNING, INFO

    days_of_supply = Column(Float, nullable=True)
    projected_stockout_date = Column(DateTime(timezone=True), nullable=True)
    explanation = Column(Text, nullable=False)

    is_acknowledged = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(UTC), nullable=False)
    synthetic_data = Column(Boolean, default=True, nullable=False)

    # Relationships
    location = relationship("Location")
    item = relationship("SupplyItem")

    def __repr__(self) -> str:
        return f"<Alert(type='{self.alert_type}', severity='{self.severity}', loc='{self.location_id}')>"
