"""DemandForecast SQLAlchemy model."""

import uuid
from datetime import UTC, datetime

from sqlalchemy import Boolean, CheckConstraint, Column, Date, DateTime, Float, ForeignKey, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.db.base import Base


class DemandForecast(Base):
    """
    Predictive consumption forecast generated by ML models in Phase 4.
    Includes bounds and explainable feature contributions.
    """

    __tablename__ = "demand_forecasts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    location_id = Column(UUID(as_uuid=True), ForeignKey("locations.id", ondelete="CASCADE"), nullable=False, index=True)
    item_id = Column(UUID(as_uuid=True), ForeignKey("supply_items.id", ondelete="CASCADE"), nullable=False, index=True)

    forecast_date = Column(Date, nullable=False, index=True)
    predicted_quantity = Column(Float, nullable=False)
    lower_bound = Column(Float, nullable=True)
    upper_bound = Column(Float, nullable=True)

    model_version = Column(String(50), nullable=False)
    generated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(UTC), nullable=False)
    feature_contributions = Column(JSONB, nullable=True)  # Explainability SHAP values/features

    synthetic_data = Column(Boolean, default=True, nullable=False)

    # Relationships
    location = relationship("Location")
    item = relationship("SupplyItem")

    __table_args__ = (CheckConstraint("predicted_quantity >= 0", name="chk_forecast_quantity_non_negative"),)

    def __repr__(self) -> str:
        return f"<DemandForecast(loc='{self.location_id}', item='{self.item_id}', date='{self.forecast_date}', qty={self.predicted_quantity})>"
