"""001_initial_schema

Revision ID: 74181405c1b2
Revises:
Create Date: 2026-10-03 15:18:27.825224

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74181405c1b2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("location_type", sa.String(length=50), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "coordinates",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("elevation_m", sa.Float(), nullable=False),
        sa.Column("synthetic_data", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_locations_code"), "locations", ["code"], unique=True)
    op.create_index(op.f("ix_locations_location_type"), "locations", ["location_type"], unique=False)
    op.create_index(op.f("ix_locations_synthetic_data"), "locations", ["synthetic_data"], unique=False)
    op.create_table(
        "optimization_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("solver_version", sa.String(length=50), nullable=False),
        sa.Column("input_configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("synthetic_data", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "supply_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("unit_weight_kg", sa.Float(), nullable=False),
        sa.Column("unit_volume_m3", sa.Float(), nullable=False),
        sa.Column("is_critical", sa.Boolean(), nullable=False),
        sa.Column("shelf_life_days", sa.Integer(), nullable=True),
        sa.Column("synthetic_data", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_supply_items_category"), "supply_items", ["category"], unique=False)
    op.create_index(op.f("ix_supply_items_sku"), "supply_items", ["sku"], unique=True)
    op.create_table(
        "alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=True),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("days_of_supply", sa.Float(), nullable=True),
        sa.Column("projected_stockout_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("is_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synthetic_data", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["supply_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False)
    op.create_index(op.f("ix_alerts_item_id"), "alerts", ["item_id"], unique=False)
    op.create_index(op.f("ix_alerts_location_id"), "alerts", ["location_id"], unique=False)
    op.create_index(op.f("ix_alerts_severity"), "alerts", ["severity"], unique=False)
    op.create_table(
        "consumption_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("recorded_date", sa.Date(), nullable=False),
        sa.Column("quantity_consumed", sa.Float(), nullable=False),
        sa.Column("weather_temp_c", sa.Float(), nullable=True),
        sa.Column("snowfall_cm", sa.Float(), nullable=True),
        sa.Column("rainfall_mm", sa.Float(), nullable=True),
        sa.Column("operational_scenario", sa.String(length=50), nullable=False),
        sa.Column("data_source_type", sa.String(length=50), nullable=False),
        sa.Column("synthetic_data", sa.Boolean(), nullable=False),
        sa.CheckConstraint("quantity_consumed >= 0", name="chk_consumption_non_negative"),
        sa.ForeignKeyConstraint(["item_id"], ["supply_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("location_id", "item_id", "recorded_date", name="uq_consumption_loc_item_date"),
    )
    op.create_index(
        "ix_consumption_query", "consumption_records", ["location_id", "item_id", "recorded_date"], unique=False
    )
    op.create_index(op.f("ix_consumption_records_item_id"), "consumption_records", ["item_id"], unique=False)
    op.create_index(op.f("ix_consumption_records_location_id"), "consumption_records", ["location_id"], unique=False)
    op.create_index(
        op.f("ix_consumption_records_recorded_date"), "consumption_records", ["recorded_date"], unique=False
    )
    op.create_table(
        "demand_forecasts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("forecast_date", sa.Date(), nullable=False),
        sa.Column("predicted_quantity", sa.Float(), nullable=False),
        sa.Column("lower_bound", sa.Float(), nullable=True),
        sa.Column("upper_bound", sa.Float(), nullable=True),
        sa.Column("model_version", sa.String(length=50), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("feature_contributions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("synthetic_data", sa.Boolean(), nullable=False),
        sa.CheckConstraint("predicted_quantity >= 0", name="chk_forecast_quantity_non_negative"),
        sa.ForeignKeyConstraint(["item_id"], ["supply_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_demand_forecasts_forecast_date"), "demand_forecasts", ["forecast_date"], unique=False)
    op.create_index(op.f("ix_demand_forecasts_item_id"), "demand_forecasts", ["item_id"], unique=False)
    op.create_index(op.f("ix_demand_forecasts_location_id"), "demand_forecasts", ["location_id"], unique=False)
    op.create_table(
        "inventory",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("reserved_quantity", sa.Float(), nullable=False),
        sa.Column("safety_stock", sa.Float(), nullable=False),
        sa.Column("max_capacity", sa.Float(), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("max_capacity >= quantity", name="chk_inventory_max_capacity_gte_quantity"),
        sa.CheckConstraint("quantity >= 0", name="chk_inventory_quantity_non_negative"),
        sa.CheckConstraint("reserved_quantity <= quantity", name="chk_inventory_reserved_lte_quantity"),
        sa.CheckConstraint("reserved_quantity >= 0", name="chk_inventory_reserved_non_negative"),
        sa.CheckConstraint("safety_stock >= 0", name="chk_inventory_safety_non_negative"),
        sa.ForeignKeyConstraint(["item_id"], ["supply_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("location_id", "item_id", name="uq_inventory_location_item"),
    )
    op.create_index(op.f("ix_inventory_item_id"), "inventory", ["item_id"], unique=False)
    op.create_index(op.f("ix_inventory_location_id"), "inventory", ["location_id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("optimization_run_id", sa.UUID(), nullable=False),
        sa.Column("recommendation_type", sa.String(length=50), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["optimization_run_id"], ["optimization_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendations_optimization_run_id"), "recommendations", ["optimization_run_id"], unique=False
    )
    op.create_table(
        "route_edges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("origin_location_id", sa.UUID(), nullable=False),
        sa.Column("destination_location_id", sa.UUID(), nullable=False),
        sa.Column(
            "route_geometry",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("distance_km", sa.Float(), nullable=False),
        sa.Column("nominal_travel_time_hrs", sa.Float(), nullable=False),
        sa.Column("average_slope_deg", sa.Float(), nullable=False),
        sa.Column("max_elevation_m", sa.Float(), nullable=False),
        sa.Column("road_type", sa.String(length=50), nullable=False),
        sa.Column("weather_friction_multiplier", sa.Float(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("synthetic_data", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("distance_km > 0", name="chk_route_distance_positive"),
        sa.CheckConstraint("nominal_travel_time_hrs > 0", name="chk_route_travel_time_positive"),
        sa.CheckConstraint("weather_friction_multiplier >= 1.0", name="chk_route_friction_gte_one"),
        sa.ForeignKeyConstraint(
            ["destination_location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_route_edges_destination_location_id"), "route_edges", ["destination_location_id"], unique=False
    )
    op.create_index(op.f("ix_route_edges_origin_location_id"), "route_edges", ["origin_location_id"], unique=False)
    op.create_table(
        "vehicles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vehicle_code", sa.String(length=50), nullable=False),
        sa.Column("vehicle_type", sa.String(length=50), nullable=False),
        sa.Column("home_location_id", sa.UUID(), nullable=False),
        sa.Column("current_location_id", sa.UUID(), nullable=True),
        sa.Column("payload_capacity_kg", sa.Float(), nullable=False),
        sa.Column("volume_capacity_m3", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("synthetic_data", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("payload_capacity_kg > 0", name="chk_vehicle_payload_positive"),
        sa.CheckConstraint("volume_capacity_m3 > 0", name="chk_vehicle_volume_positive"),
        sa.ForeignKeyConstraint(
            ["current_location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicles_current_location_id"), "vehicles", ["current_location_id"], unique=False)
    op.create_index(op.f("ix_vehicles_home_location_id"), "vehicles", ["home_location_id"], unique=False)
    op.create_index(op.f("ix_vehicles_vehicle_code"), "vehicles", ["vehicle_code"], unique=True)
    op.create_index(op.f("ix_vehicles_vehicle_type"), "vehicles", ["vehicle_type"], unique=False)
    op.create_table(
        "shipments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("shipment_code", sa.String(length=50), nullable=False),
        sa.Column("origin_location_id", sa.UUID(), nullable=False),
        sa.Column("destination_location_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("route_edge_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("departure_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("estimated_arrival_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_arrival_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synthetic_data", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["destination_location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_edge_id"],
            ["route_edges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shipments_destination_location_id"), "shipments", ["destination_location_id"], unique=False
    )
    op.create_index(op.f("ix_shipments_origin_location_id"), "shipments", ["origin_location_id"], unique=False)
    op.create_index(op.f("ix_shipments_route_edge_id"), "shipments", ["route_edge_id"], unique=False)
    op.create_index(op.f("ix_shipments_shipment_code"), "shipments", ["shipment_code"], unique=True)
    op.create_index(op.f("ix_shipments_vehicle_id"), "shipments", ["vehicle_id"], unique=False)
    op.create_table(
        "shipment_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("shipment_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.CheckConstraint("quantity > 0", name="chk_shipment_item_quantity_positive"),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["supply_items.id"],
        ),
        sa.ForeignKeyConstraint(["shipment_id"], ["shipments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shipment_items_item_id"), "shipment_items", ["item_id"], unique=False)
    op.create_index(op.f("ix_shipment_items_shipment_id"), "shipment_items", ["shipment_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shipment_items_shipment_id"), table_name="shipment_items")
    op.drop_index(op.f("ix_shipment_items_item_id"), table_name="shipment_items")
    op.drop_table("shipment_items")
    op.drop_index(op.f("ix_shipments_vehicle_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_shipment_code"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_route_edge_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_origin_location_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_destination_location_id"), table_name="shipments")
    op.drop_table("shipments")
    op.drop_index(op.f("ix_vehicles_vehicle_type"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_vehicle_code"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_home_location_id"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_current_location_id"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_route_edges_origin_location_id"), table_name="route_edges")
    op.drop_index(op.f("ix_route_edges_destination_location_id"), table_name="route_edges")
    op.drop_table("route_edges")
    op.drop_index(op.f("ix_recommendations_optimization_run_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_inventory_location_id"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_item_id"), table_name="inventory")
    op.drop_table("inventory")
    op.drop_index(op.f("ix_demand_forecasts_location_id"), table_name="demand_forecasts")
    op.drop_index(op.f("ix_demand_forecasts_item_id"), table_name="demand_forecasts")
    op.drop_index(op.f("ix_demand_forecasts_forecast_date"), table_name="demand_forecasts")
    op.drop_table("demand_forecasts")
    op.drop_index(op.f("ix_consumption_records_recorded_date"), table_name="consumption_records")
    op.drop_index(op.f("ix_consumption_records_location_id"), table_name="consumption_records")
    op.drop_index(op.f("ix_consumption_records_item_id"), table_name="consumption_records")
    op.drop_index("ix_consumption_query", table_name="consumption_records")
    op.drop_table("consumption_records")
    op.drop_index(op.f("ix_alerts_severity"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_location_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_item_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_supply_items_sku"), table_name="supply_items")
    op.drop_index(op.f("ix_supply_items_category"), table_name="supply_items")
    op.drop_table("supply_items")
    op.drop_table("optimization_runs")
    op.drop_index(op.f("ix_locations_synthetic_data"), table_name="locations")
    op.drop_index(op.f("ix_locations_location_type"), table_name="locations")
    op.drop_index(op.f("ix_locations_code"), table_name="locations")
    op.drop_table("locations")
    # ### end Alembic commands ###
